### ISSUE TITLE
Resources folder missing

### ISSUE THREAD

**Issue by crshrprt** [glafiro/space-chili#1]
Thank you for this interesting plugin and for making it open source.

I was trying to build it on Linux, however in Projucer I get an error about missing resource files.

It seems that in the jucer file there is a folder called Resources, with some fonts and images, that is not present in this repo.

**Comment by glafiro** [comment]
Hi, thank you for trying out my plug-in, which is still being developed.

This commit 0275ee7827231a2b46c453d57dcb984162881f24 should fix the issue. 

It compiles for me on Ubuntu, and you can also find precompiled VST3 and LV2 versions for Linux in the Releases section. Let me know if you run into any more issues.
